### ISSUE TITLE
Reporte de Práctica DLL

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Anthony4523#2]
[Práctica 1__Librería DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Anthony4523/files/6333068/Practica.1__Libreria.DLL.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Israel Nicolás, Uzías López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
